# frozen_string_literal: true

require 'json'

module PasswordStrength
  # Renders the data the JavaScript port shares with the Ruby one: the word
  # list, the leet table, the limits and the score thresholds. `rake javascript`
  # writes the result into app/assets/javascripts/password_strength.js, and a
  # test fails when the file on disk no longer matches, so the two ports cannot
  # drift apart unnoticed.
  module JavascriptSource
    PATH = File.expand_path('../../app/assets/javascripts/password_strength.js', __dir__)
    BEGIN_MARKER = '  // BEGIN GENERATED BY `rake javascript`. Edit lib/password_strength/*.rb instead.'
    END_MARKER = '  // END GENERATED'

    class << self
      # The name each generated JavaScript variable takes, and the Ruby value
      # behind it. JavaScript has no \z, and its $ means the same thing in
      # TRAILING_DIGITS_RE because the regex carries no multiline flag.
      def values
        limits.merge(
          'TRAILING_DIGITS_RE' => "/#{Blocklist::TRAILING_DIGITS_RE.source.sub(/\\z\z/, '$')}/",
          'LEET_SUBSTITUTIONS' => JSON.generate(Blocklist::LEET_SUBSTITUTIONS),
          'COMMON_WORDS' => JSON.generate(Blocklist.common_words)
        )
      end

      def limits
        {
          'PASSWORD_LIMIT' => Base::PASSWORD_LIMIT,
          'USERNAME_LIMIT' => Base::USERNAME_LIMIT,
          'WEAK_SCORE' => Base::WEAK_SCORE,
          'STRONG_SCORE' => Base::STRONG_SCORE,
          'MAXIMUM_SCORE' => Base::MAXIMUM_SCORE,
          'SHORT_PASSWORD_SIZE' => Scoring::SHORT_PASSWORD_SIZE
        }
      end

      # The generated block, marker lines included.
      def block
        lines = values.map { |name, value| "  var #{name} = #{value};" }

        [BEGIN_MARKER, *lines, END_MARKER].join("\n")
      end

      # The whole JavaScript file with the current block in it, and the public
      # word list pointing at the generated one rather than repeating it.
      def render(current = File.read(PATH))
        current
          .sub(/^#{Regexp.escape(BEGIN_MARKER)}\n.*?^#{Regexp.escape(END_MARKER)}$/m, block)
          .sub(/^  PasswordStrength\.commonWords = .*$/, '  PasswordStrength.commonWords = COMMON_WORDS;')
      end

      def write
        File.write(PATH, render)
      end
    end
  end
end
